version: "2.4"

networks:
  activity-punch-system-backend-net:
    driver: bridge

services:
  loki:
    image: grafana/loki:2.7.1
    container_name: activity-punch-system-backend-loki
    ports:
      - 3100:3100
    volumes:
      - ./otel/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - minio
    networks:
      - activity-punch-system-backend-net

  promtail:
    image: grafana/promtail:2.7.1
    container_name: activity-punch-system-backend-promtail
    volumes:
      - ./otel/promtail.yaml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - activity-punch-system-backend-net

  grafana:
    image: grafana/grafana:latest
    container_name: activity-punch-system-backend-grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    command: -config /etc/grafana/grafana.ini
    networks:
      - activity-punch-system-backend-net

  minio:
    image: minio/minio:latest
    container_name: activity-punch-system-backend-minio
    environment:
      - MINIO_ACCESS_KEY=superuser
      - MINIO_SECRET_KEY=supersecret
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        mkdir -p /data/tempo && \
        minio server /data --console-address ':9001'
    volumes:
      - ./otel/.data/minio:/data
    networks:
      - activity-punch-system-backend-net

  tempo:
    image: grafana/tempo:latest
    container_name: activity-punch-system-backend-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./otel/tempo.yaml:/etc/tempo.yaml
      - ./otel/.data/tempo:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    restart: on-failure
    depends_on:
      - minio
    networks:
      - activity-punch-system-backend-net

  prometheus:
    image: prom/prometheus:latest
    container_name: activity-punch-system-backend-prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./otel/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - activity-punch-system-backend-net